-- ============================================
-- PAYMENT TRANSACTIONS LOG
-- Description: Audit log for all G2Pay payment transactions
-- Created: 2026-02-05
-- ============================================

-- Create payment_transactions table for audit logging
CREATE TABLE IF NOT EXISTS public.payment_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),

  -- Order reference
  order_id uuid NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,

  -- Transaction details
  transaction_id text, -- G2Pay transactionID
  transaction_unique text NOT NULL, -- Our UUID for idempotency
  amount_pence integer NOT NULL,
  currency_code integer NOT NULL DEFAULT 826, -- 826 = GBP

  -- Request/Response data
  request_data jsonb, -- Full request sent to G2Pay
  response_data jsonb, -- Full response from G2Pay

  -- Status
  status text NOT NULL, -- 'pending', 'success', 'failed', 'error'
  response_code text, -- G2Pay response code (0 = success)
  response_message text, -- G2Pay response message

  -- Signature verification
  signature_verified boolean DEFAULT false,
  signature_mismatch_reason text,

  -- Metadata
  error_message text,
  gateway_url text,

  CONSTRAINT valid_status CHECK (status IN ('pending', 'success', 'failed', 'error'))
);

-- Indexes for efficient lookups
CREATE INDEX IF NOT EXISTS idx_payment_transactions_order_id ON public.payment_transactions(order_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_user_id ON public.payment_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_transaction_id ON public.payment_transactions(transaction_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_transaction_unique ON public.payment_transactions(transaction_unique);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_status ON public.payment_transactions(status);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_created_at ON public.payment_transactions(created_at DESC);

-- RLS Policies
ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;

-- Users can view their own payment transactions
CREATE POLICY "Users can view own payment transactions"
ON public.payment_transactions FOR SELECT
TO authenticated
USING (user_id = auth.uid());

-- Only service role can insert/update (edge functions)
CREATE POLICY "Service role can manage payment transactions"
ON public.payment_transactions FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Admins can view all transactions
CREATE POLICY "Admins can view all payment transactions"
ON public.payment_transactions FOR SELECT
TO authenticated
USING (public.is_admin());

COMMENT ON TABLE public.payment_transactions IS 'Audit log for all G2Pay payment transactions';
COMMENT ON COLUMN public.payment_transactions.transaction_unique IS 'Unique transaction ID generated by us for idempotency';
COMMENT ON COLUMN public.payment_transactions.signature_verified IS 'Whether G2Pay response signature was verified successfully';
